# -*- coding: utf-8 -*-
"""find-latitude-longitude.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qgjlLDDfnfkNVNvSEIcfPkrRaJIwbGD0
"""

import geocoder
import pandas as pd


def analiz_sutun(x):  # Belirtilen Sütunlardaki Verileri Bir Tablo Listesine Ekliyoruz
    tablo = []

    for i in range(len(dosya.index)):
        tablo.append(dosya.loc[[i], x].values[0] + " " +  ek)
        i += 1
    return tablo

def find_latitude_longitude(analiz_sutun, api): # analiz_sutun() fonksiyonunda topladığımız verilerin burada konumlarını buluyoruz
    
    latitude_longitude = []
    latitude = []
    longitude = []
    baraj_adi = []
    for i in analiz_sutun:
      
        g = geocoder.google(i , key = api )
        latitude_longitude.append(g.latlng)
        print(i)
        baraj_adi.append(i)

    x = 0
    for a in latitude_longitude:
      if a != None:
        latitude.append(latitude_longitude[x][0])
        longitude.append(latitude_longitude[x][1])
        x += 1
      else:
        latitude.append(None)
        longitude.append(None)
        x += 1
       
    data = { "Location":baraj_adi, "Latitude":latitude, "Longitude": longitude}
    df = pd.DataFrame(data)
    print("---------------------------------")
    print(df)

    while True:

      try:
        yesNo = str(input("Sonucu Excel Tablosu Olarak İster Misiniz? [E/H]"))

        if (yesNo == "E"):
          outputName = input("Dosyanın Adı Ne Olsun?")
          df.to_excel(outputName+".xlsx") 
          print("Dosyanız Oluşturuldu!" + outputName+".xlsx")
          break

        elif (yesNo == "H"):
          break

      except NameError:
        print("Geçersiz Seçim")



input_Api = input("Google API key giriniz: ")
api = input_Api # Google api keyi giriniz!!!!!

while True:

  try:
    dosyanin_Adi = str(input("Excel Dosyasının Yolunu Girin: "))
    dosya = pd.read_excel(dosyanin_Adi)  # Tablonuzun konumunu girin

    df = pd.DataFrame(dosya)

    print(df.head())
    print("---------------------------------")  
    break
  except FileNotFoundError:
    print("Dosya Bulunamadı")
  except IsADirectoryError:
      print("Bu bir klasör. Lütfen dosya yolu girin.")

sutunun_adi = str(input("Adres Verilerin Olduğu Sütunun Adını Girin: "))
ek = str(input("Eklemek istediğiniz bir ek var mı? Örneğin ('...Barajı', '...Yolu', '...Parkı') YOKSA BOŞ BIRAKIN : "))

print("---------------------------------")


find_latitude_longitude(analiz_sutun(sutunun_adi), api)